import {
    Search,
    BarChart,
    LineChart,
    Globe,
    Code,
    Server,
    Database,
    ShoppingCart,
    CreditCard,
    Package,
    Palette,
    Layers,
    Eye,
    Monitor,
    Share2,
    Mail,
    FileText,
  } from "lucide-react"
  
  export const services = [
    {
      id: "web-development",
      slug: "web-development",
      title: "Web Development",
      description:
        "Custom websites and web applications built with modern technologies to help your business stand out and succeed online.",
      heroImage: "./assets/AlberowWebsite.webp",
      overviewText: "We offer a comprehensive range of web development services to meet your business needs",
      features: [
        {
          title: "Frontend Development",
          description: "Beautiful, responsive user interfaces built with modern frameworks like React and Next.js.",
          icon: Code,
          iconColor: "text-blue-500",
          bulletPoints: ["Responsive Design", "Interactive UI/UX", "Performance Optimization"],
        },
        {
          title: "Backend Development",
          description: "Robust server-side solutions that power your applications with security and scalability.",
          icon: Server,
          iconColor: "text-purple-500",
          bulletPoints: ["API Development", "Authentication Systems", "Server Management"],
        },
        {
          title: "Database Solutions",
          description: "Efficient data storage and management systems tailored to your specific needs.",
          icon: Database,
          iconColor: "text-pink-500",
          bulletPoints: ["Database Design", "Data Migration", "Performance Tuning"],
        },
        {
          title: "E-commerce Solutions",
          description: "Complete online store solutions with secure payment processing and inventory management.",
          icon: ShoppingCart,
          iconColor: "text-cyan-500",
          bulletPoints: ["Shopping Cart Integration", "Payment Gateway Setup", "Product Management"],
        },
        {
          title: "CMS Development",
          description: "Custom content management systems that make updating your website simple and efficient.",
          icon: FileText,
          iconColor: "text-green-500",
          bulletPoints: ["User-friendly Interfaces", "Content Workflows", "Media Management"],
        },
        {
          title: "Web Application Development",
          description: "Custom web applications that automate processes and improve business efficiency.",
          icon: Server,
          iconColor: "text-amber-500",
          bulletPoints: ["SaaS Applications", "Business Process Automation", "Custom Dashboards"],
        },
      ],
      processTitle: "Development Process",
      processDescription: "We follow a structured approach to deliver high-quality web solutions",
      process: [
        {
          title: "Discovery",
          description: "We learn about your business, goals, and requirements to create a tailored solution.",
          bgColor: "bg-blue-500/10",
          textColor: "text-blue-500",
        },
        {
          title: "Planning",
          description: "We create a detailed roadmap with timelines, milestones, and deliverables.",
          bgColor: "bg-purple-500/10",
          textColor: "text-purple-500",
        },
        {
          title: "Development",
          description: "Our team builds your solution using the latest technologies and best practices.",
          bgColor: "bg-pink-500/10",
          textColor: "text-pink-500",
        },
        {
          title: "Launch & Support",
          description: "We deploy your solution and provide ongoing maintenance and support.",
          bgColor: "bg-cyan-500/10",
          textColor: "text-cyan-500",
        },
      ],
      ctaTitle: "Ready to Start Your Web Development Project?",
      ctaDescription: "Contact us today to discuss your requirements and get a free consultation.",
    },
    {
      id: "digital-marketing",
      slug: "digital-marketing",
      title: "Digital Marketing",
      description:
        "Strategic marketing solutions to increase your online visibility, drive traffic, and grow your business.",
      heroImage: "/placeholder.svg?height=600&width=800&text=Digital+Marketing",
      overviewText: "Comprehensive digital marketing solutions to help your business grow online",
      features: [
        {
          title: "Search Engine Optimization",
          description: "Improve your search engine rankings and drive organic traffic to your website.",
          icon: Search,
          iconColor: "text-blue-500",
          bulletPoints: ["Keyword Research", "On-Page Optimization", "Link Building"],
        },
        {
          title: "Social Media Marketing",
          description: "Build your brand presence and engage with your audience on social media platforms.",
          icon: Share2,
          iconColor: "text-purple-500",
          bulletPoints: ["Content Strategy", "Community Management", "Paid Social Campaigns"],
        },
        {
          title: "Pay-Per-Click Advertising",
          description: "Drive targeted traffic to your website with strategic paid advertising campaigns.",
          icon: BarChart,
          iconColor: "text-pink-500",
          bulletPoints: ["Google Ads", "Display Advertising", "Remarketing"],
        },
        {
          title: "Email Marketing",
          description: "Connect with your audience directly and drive conversions with targeted email campaigns.",
          icon: Mail,
          iconColor: "text-cyan-500",
          bulletPoints: ["Campaign Strategy", "Email Automation", "Performance Analysis"],
        },
        {
          title: "Content Marketing",
          description: "Create valuable content that attracts, engages, and converts your target audience.",
          icon: FileText,
          iconColor: "text-green-500",
          bulletPoints: ["Content Strategy", "Blog Writing", "Content Distribution"],
        },
        {
          title: "Analytics & Reporting",
          description: "Track, analyze, and optimize your marketing performance with data-driven insights.",
          icon: LineChart,
          iconColor: "text-amber-500",
          bulletPoints: ["Performance Tracking", "Custom Reporting", "Conversion Optimization"],
        },
      ],
      processTitle: "Marketing Process",
      processDescription: "We follow a data-driven approach to deliver results",
      process: [
        {
          title: "Research",
          description: "We analyze your market, competitors, and target audience to develop effective strategies.",
          bgColor: "bg-blue-500/10",
          textColor: "text-blue-500",
        },
        {
          title: "Strategy",
          description: "We create a customized marketing plan aligned with your business goals.",
          bgColor: "bg-purple-500/10",
          textColor: "text-purple-500",
        },
        {
          title: "Implementation",
          description: "We execute the strategy across relevant channels to reach your target audience.",
          bgColor: "bg-pink-500/10",
          textColor: "text-pink-500",
        },
        {
          title: "Optimization",
          description: "We continuously monitor, analyze, and refine our approach to maximize results.",
          bgColor: "bg-cyan-500/10",
          textColor: "text-cyan-500",
        },
      ],
      ctaTitle: "Ready to Grow Your Online Presence?",
      ctaDescription: "Contact us today to discuss your digital marketing needs and get a free consultation.",
    },
    {
      id: "ui-ux-design",
      slug: "ui-ux-design",
      title: "UI/UX Design",
      description: "User-centered design that enhances user experience, increases engagement, and drives conversions.",
      heroImage: "/placeholder.svg?height=600&width=800&text=UI/UX+Design",
      overviewText: "Comprehensive design solutions to create intuitive and engaging user experiences",
      features: [
        {
          title: "User Interface Design",
          description: "Beautiful, intuitive interfaces that align with your brand and delight your users.",
          icon: Palette,
          iconColor: "text-blue-500",
          bulletPoints: ["Visual Design", "Responsive Layouts", "Design Systems"],
        },
        {
          title: "User Experience Design",
          description: "Strategic design that focuses on creating meaningful and relevant experiences for users.",
          icon: Eye,
          iconColor: "text-purple-500",
          bulletPoints: ["User Research", "Information Architecture", "User Journey Mapping"],
        },
        {
          title: "Wireframing & Prototyping",
          description: "Create and test your product before development to save time and resources.",
          icon: Layers,
          iconColor: "text-pink-500",
          bulletPoints: ["Low-fidelity Wireframes", "Interactive Prototypes", "User Testing"],
        },
        {
          title: "Responsive Design",
          description: "Ensure your digital products look and function perfectly across all devices and screen sizes.",
          icon: Monitor,
          iconColor: "text-cyan-500",
          bulletPoints: ["Mobile-First Design", "Cross-Device Compatibility", "Adaptive Layouts"],
        },
        {
          title: "Brand Identity Design",
          description: "Create a cohesive visual identity that communicates your brand's values and personality.",
          icon: Palette,
          iconColor: "text-green-500",
          bulletPoints: ["Logo Design", "Color Palette", "Typography"],
        },
        {
          title: "Usability Testing",
          description: "Evaluate your product with real users to identify issues and improve the user experience.",
          icon: Eye,
          iconColor: "text-amber-500",
          bulletPoints: ["User Testing Sessions", "Heuristic Evaluation", "Feedback Analysis"],
        },
      ],
      processTitle: "Design Process",
      processDescription: "We follow a user-centered design approach to create effective solutions",
      process: [
        {
          title: "Research",
          description: "We understand your users, business goals, and market to inform our design decisions.",
          bgColor: "bg-blue-500/10",
          textColor: "text-blue-500",
        },
        {
          title: "Design",
          description: "We create wireframes, prototypes, and visual designs based on research insights.",
          bgColor: "bg-purple-500/10",
          textColor: "text-purple-500",
        },
        {
          title: "Test",
          description: "We validate our designs with real users to ensure they meet their needs and expectations.",
          bgColor: "bg-pink-500/10",
          textColor: "text-pink-500",
        },
        {
          title: "Refine",
          description: "We iterate on our designs based on feedback to create the best possible solution.",
          bgColor: "bg-cyan-500/10",
          textColor: "text-cyan-500",
        },
      ],
      ctaTitle: "Ready to Enhance Your User Experience?",
      ctaDescription: "Contact us today to discuss your UI/UX design needs and get a free consultation.",
    },
    {
      id: "ecommerce",
      slug: "ecommerce",
      title: "E-commerce Solutions",
      description: "Custom online store solutions that drive sales, enhance customer experience, and grow your business.",
      heroImage: "/placeholder.svg?height=600&width=800&text=E-commerce",
      overviewText: "Comprehensive e-commerce solutions to help your business sell online",
      features: [
        {
          title: "E-commerce Website Development",
          description: "Custom online stores built with the latest technologies and best practices.",
          icon: ShoppingCart,
          iconColor: "text-blue-500",
          bulletPoints: ["Custom Design", "Mobile Optimization", "SEO-Friendly Structure"],
        },
        {
          title: "Payment Gateway Integration",
          description: "Secure and seamless payment processing solutions for your online store.",
          icon: CreditCard,
          iconColor: "text-purple-500",
          bulletPoints: ["Multiple Payment Options", "Secure Transactions", "International Payments"],
        },
        {
          title: "Inventory Management",
          description: "Efficient inventory tracking and management systems for your products.",
          icon: Package,
          iconColor: "text-pink-500",
          bulletPoints: ["Real-time Stock Updates", "Product Categorization", "Low Stock Alerts"],
        },
        {
          title: "E-commerce Analytics",
          description: "Data-driven insights to optimize your online store performance and sales.",
          icon: BarChart,
          iconColor: "text-cyan-500",
          bulletPoints: ["Sales Reporting", "Customer Behavior Analysis", "Conversion Optimization"],
        },
        {
          title: "Shopping Cart Optimization",
          description: "Streamlined checkout processes to reduce cart abandonment and increase conversions.",
          icon: ShoppingCart,
          iconColor: "text-green-500",
          bulletPoints: ["One-Page Checkout", "Guest Checkout Option", "Abandoned Cart Recovery"],
        },
        {
          title: "Product Management",
          description: "Effective tools to manage your product catalog, pricing, and promotions.",
          icon: Package,
          iconColor: "text-amber-500",
          bulletPoints: ["Bulk Product Upload", "Discount Management", "Product Variants"],
        },
      ],
      processTitle: "E-commerce Development Process",
      processDescription: "We follow a structured approach to create successful online stores",
      process: [
        {
          title: "Discovery",
          description: "We understand your business, products, target audience, and e-commerce goals.",
          bgColor: "bg-blue-500/10",
          textColor: "text-blue-500",
        },
        {
          title: "Design & Development",
          description: "We create a custom online store that reflects your brand and meets your requirements.",
          bgColor: "bg-purple-500/10",
          textColor: "text-purple-500",
        },
        {
          title: "Testing & Launch",
          description: "We thoroughly test your store and ensure a smooth launch to the public.",
          bgColor: "bg-pink-500/10",
          textColor: "text-pink-500",
        },
        {
          title: "Support & Growth",
          description: "We provide ongoing support and optimization to help your online store grow.",
          bgColor: "bg-cyan-500/10",
          textColor: "text-cyan-500",
        },
      ],
      ctaTitle: "Ready to Start Selling Online?",
      ctaDescription: "Contact us today to discuss your e-commerce project and get a free consultation.",
    },
    {
      id: "seo",
      slug: "seo",
      title: "SEO Optimization",
      description: "Improve your search engine rankings, drive organic traffic, and increase your online visibility.",
      heroImage: "/placeholder.svg?height=600&width=800&text=SEO+Optimization",
      overviewText: "Comprehensive SEO solutions to improve your search engine rankings and drive organic traffic",
      features: [
        {
          title: "Keyword Research & Strategy",
          description: "Identify the most valuable keywords for your business and create a targeted SEO strategy.",
          icon: Search,
          iconColor: "text-blue-500",
          bulletPoints: ["Competitor Analysis", "Search Volume Analysis", "Long-tail Keyword Targeting"],
        },
        {
          title: "On-Page SEO",
          description: "Optimize your website's content and structure to improve search engine rankings.",
          icon: Globe,
          iconColor: "text-purple-500",
          bulletPoints: ["Content Optimization", "Meta Tags Optimization", "URL Structure Improvement"],
        },
        {
          title: "Technical SEO",
          description: "Improve your website's technical aspects to enhance search engine crawling and indexing.",
          icon: LineChart,
          iconColor: "text-pink-500",
          bulletPoints: ["Site Speed Optimization", "Mobile Responsiveness", "Schema Markup Implementation"],
        },
        {
          title: "Link Building",
          description: "Build high-quality backlinks to increase your website's authority and rankings.",
          icon: Globe,
          iconColor: "text-cyan-500",
          bulletPoints: ["Content Outreach", "Guest Posting", "Broken Link Building"],
        },
        {
          title: "SEO Auditing",
          description: "Comprehensive analysis of your website to identify and fix SEO issues.",
          icon: BarChart,
          iconColor: "text-green-500",
          bulletPoints: ["Technical Issue Identification", "Content Gap Analysis", "Competitor Benchmarking"],
        },
        {
          title: "Local SEO",
          description: "Improve your visibility in local search results to attract nearby customers.",
          icon: BarChart,
          iconColor: "text-amber-500",
          bulletPoints: ["Google Business Profile Optimization", "Local Citation Building", "Review Management"],
        },
      ],
      processTitle: "SEO Process",
      processDescription: "We follow a data-driven approach to improve your search engine rankings",
      process: [
        {
          title: "Audit & Analysis",
          description: "We analyze your website, competitors, and target keywords to identify opportunities.",
          bgColor: "bg-blue-500/10",
          textColor: "text-blue-500",
        },
        {
          title: "Strategy Development",
          description: "We create a customized SEO strategy based on our findings and your business goals.",
          bgColor: "bg-purple-500/10",
          textColor: "text-purple-500",
        },
        {
          title: "Implementation",
          description: "We execute the strategy by optimizing your website and building your online presence.",
          bgColor: "bg-pink-500/10",
          textColor: "text-pink-500",
        },
        {
          title: "Monitoring & Refinement",
          description: "We track your performance and continuously refine our approach to maximize results.",
          bgColor: "bg-cyan-500/10",
          textColor: "text-cyan-500",
        },
      ],
      ctaTitle: "Ready to Improve Your Search Rankings?",
      ctaDescription: "Contact us today to discuss your SEO needs and get a free consultation.",
    },
  ]
  
  export function getServiceBySlug(slug) {
    return services.find((service) => service.slug === slug)
  }
  
  export function getAllServiceSlugs() {
    return services.map((service) => service.slug)
  }
  